---
version: '3'
services:
        maven:
            build:
                context: ./
                dockerfile: maven.Dockerfile
            volumes:
                - war-files:/boxfuse-sample-java-war-hello/target


        tomcat:
            image: tomcat:9.0
            ports:
                - '8080:8080'
            depends_on:
                - maven
            volumes:
              - war-files:/usr/local/tomcat/webapps/
volumes:
  war-files: