---
- name: Provisioning builder
  hosts: web
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Replace the title in the HTML file
      lineinfile:
        path: /var/www/html/index.html
        regexp: '<title>.*</title>'
        line: "<title><script>document.write(new Date().toLocaleDateString());</script></title>"
        state: present